version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: unbookinho
      MYSQL_USER: team_user
      MYSQL_PASSWORD: team_pass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
