version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db_container
    environment:
      POSTGRES_USER: team_user
      POSTGRES_PASSWORD: team_pass
      POSTGRES_DB: unbookinho
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
