version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: team_user
      MYSQL_PASSWORD: team_pass
      MYSQL_DATABASE: unbookinho
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: