site_name: UNBookinho
repo_url: https://github.com/unb-mds/2024-2-Squad01

nav:
  - Home: index.md
  - Como contribuir?: contributing.md
  - Como executar o projeto?: executing.md
  - Sprints:
    - Sprint 0: sprints/sprint-0.md
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    
    - Front-end:

  - API: api.md
  - Arquitetura: architecture.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

  palette:
    primary: "indigo"

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences